### ISSUE TITLE
Incomplete behavior ?

### ISSUE THREAD

**Issue by eilgin** [watilde/parse-error#3]
First, thanks for having made this project before me so i don't have to!

Anyway, i've fiddled a little with your package but it seems that some properties aren't properly set such as "line", "column". For example i've tried this:

```js
const parseError = require("parse-error");
class TypingError extends Error {};
parseError(new TypingError("blip"));
```

And got an object with the following properties:
```
arguments: undefined
filename: undefined
line: NaN
message: "blip"
row: NaN
stack: `
Error: blip
    at /app/index.js:26:29
    at Generator.next (<anonymous>)
    at runkit-runtime:4291:66
    at Generator.next (<anonymous>)
    at iterate (runkit-runtime:4305:77)
    at module.exports (runkit-runtime:4319:19)
    at runkit-runtime:4402:7
    at runkit-runtime:4403:3
    at Object.<anonymous> (runkit-runtime:8:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
`
type: "Error"
```
([runkit](https://runkit.com/eilgin/parse-error))

We can see at the second line of `stack` the line and column of the source (respectively 26 and 29). This value is quite standardized (using [v8 API](https://github.com/v8/v8/wiki/Stack-Trace-API)).
The `type` value is also wrong as it should be `TypingError` (which derived from the `Error`).

I've got some improvement ideas for this package:
- why not display the stack as an array instead of the classic string value (each element could be either the string of the current stack of an object containing the filename, the row and column where the emitted error appeared) ?
- why not create a `toString()` method which could print a "pretty-printed" version of the error ?

;)

**Comment by watilde** [comment]
Agreed on what you said :)
